default:
  just --list

home profile:
  git add .
  home-manager switch --flake .#{{profile}}

nix host:
  git add .
  sudo nixos-rebuild switch --flake .#{{host}}

update package="":
  nix flake update #{{package}}

history:
  nix profile history --profile /nix/var/nix/profiles/system

clean:
  # remove all generations older than 7 days
  sudo nix profile wipe-history --profile /nix/var/nix/profiles/system  --older-than 7d

gc:
  # garbage collect all unused nix store entries
  sudo nix-collect-garbage --delete-old
