default:
  just --list

[group("home-manager")]
home-switch profile:
  git add .
  home-manager switch --flake .#{{profile}}

[group("home-manager")]
home-switch-dry profile:
  git add .
  home-manager build --flake .#{{profile}} --dry-run

[group("home-manager")]
home-build-compare profile:
  git add .
  nix build .#homeConfigurations.{{profile}}.activationPackage --out-link ./result-home
  nix shell nixpkgs#nvd -c nvd diff ~/.local/state/nix/profiles/home-manager ./result-home

[group("nix")]
nix-switch host:
  git add .
  sudo nixos-rebuild switch --flake .#{{host}}

[group("nix")]
nix-switch-dry host:
  git add .
  sudo nixos-rebuild dry-activate --flake .#{{host}}

[group("nix")]
nix-update package="":
  nix flake update {{package}}

[group("nix")]
nix-history:
  nix profile history --profile /nix/var/nix/profiles/system

[group("nix")]
nix-clean:
  # remove all generations older than 7 days
  sudo nix profile wipe-history --profile /nix/var/nix/profiles/system  --older-than 7d

[group("nix")]
nix-gc:
  # garbage collect all unused nix store entries
  sudo nix-collect-garbage --delete-old

[group("nix")]
nix-build host:
  nix build .#nixosConfigurations.{{host}}.config.system.build.toplevel

[group("nix")]
nix-build-compare host:
  git add .
  nix build .#nixosConfigurations.{{host}}.config.system.build.toplevel --out-link ./result-system
  nix shell nixpkgs#nvd -c nvd diff /run/current-system ./result-system

[group("nix")]
nix-build-vm host:
  nix build .#nixosConfigurations.{{host}}.config.system.build.vm

[group("nix")]
nix-build-iso:
  nix build .#nixosConfigurations.iso.config.system.build.isoImage

[group("nix")]
nix-switch-remote host user ip:
  nixos-rebuild switch --flake .#{{host}} --target-host {{user}}@{{ip}} --sudo --ask-sudo-password
