default:
  just --list

[group("home-manager")]
hm-switch profile:
  git add .
  home-manager switch --flake .#{{profile}}

[group("nix")]
nix-switch host:
  git add .
  sudo nixos-rebuild switch --flake .#{{host}}

[group("nix")]
nix-update package="":
  nix flake update {{package}}

[group("nix")]
nix-history:
  nix profile history --profile /nix/var/nix/profiles/system

[group("nix")]
nix-clean:
  # remove all generations older than 7 days
  sudo nix profile wipe-history --profile /nix/var/nix/profiles/system  --older-than 7d

[group("nix")]
nix-gc:
  # garbage collect all unused nix store entries
  sudo nix-collect-garbage --delete-old

[group("nix")]
nix-build-vm host:
  nix build .#nixosConfigurations.{{host}}.config.system.build.vm

[group("nix")]
nix-build-iso:
  nix build .#nixosConfigurations.iso.config.system.build.isoImage
